(function(){var d=window,f=document,h=parseInt,l="items",m="split",q="push",r="length",u="prototype",v,w=this,x=function(a,c,b){a=a[m](".");b=b||w;a[0]in b||!b.execScript||b.execScript("var "+a[0]);for(var e;a[r]&&(e=a.shift());)a[r]||void 0===c?b=b[e]?b[e]:b[e]={}:b[e]=c},y=Date.now||function(){return+new Date};var z=function(a){this.s=a},B=/\s*;\s*/;v=z[u];v.isEnabled=function(){return navigator.cookieEnabled};v.S=function(a){return!/[;=\s]/.test(a)};v.T=function(a){return!/[;\r\n]/.test(a)};
v.set=function(a,c,b,e,g,k){if(!this.S(a))throw Error('Invalid cookie name "'+a+'"');if(!this.T(c))throw Error('Invalid cookie value "'+c+'"');void 0!==b||(b=-1);g=g?";domain="+g:"";e=e?";path="+e:"";k=k?";secure":"";b=0>b?"":0==b?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(y()+1E3*b)).toUTCString();this.Z(a+"="+c+g+e+b+k)};v.M=function(){return this.v().keys};v.P=function(){return this.v().values};v.Z=function(a){this.s.cookie=a};v.N=function(){return(this.s.cookie||"")[m](B)};
v.v=function(){for(var a=this.N(),c=[],b=[],e,g,k=0;g=a[k];k++)e=g.indexOf("="),-1==e?(c[q](""),b[q](g)):(c[q](g.substring(0,e)),b[q](g.substring(e+1)));return{keys:c,values:b}};var C={},D=function(a,c,b){this.b=a;this.A=c;this.r=b;this.m=Math.floor((new Date).getTime()/1E3);this.j=8035200;this.g=void 0};D[u].ba=function(){return this.b+"$"+this.A+":"+this.r};D[u].ca=function(){var a=this.b+"$"+this.A+":"+this.m+":"+this.j;"string"==typeof this.g&&(a=a.concat(":",this.g));return a};D[u].aa=function(a,c,b){this.m=a;this.j=c;this.g=b};D[u].R=function(){return(new Date).getTime()>(new Date(1E3*(this.m+this.j))).getTime()};
var G=function(a){var c={},b=new z(f);if(!b.isEnabled())return c;var e=b.M(),b=b.P();if(null==e||null==b)return c;for(var g=0;g<e[r];g++)if("__utmx"==e[g])for(var k=F(b[g],a),p=0;p<k[r];p++){var n=/([^$]+)\$([^:]+):(.*)/.exec(k[p]);null!==n&&4==n[r]&&(n=new D(n[1],n[2],n[3]),c[n.b]=n)}g={};for(k=0;k<e[r];k++)if("__utmxx"==e[k])for(p=F(b[k],a),n=0;n<p[r];n++){var t=/([^$]+)\$([^:]+):([^:]+):([^:]+):?(.*)/.exec(p[n]);if(null!==t&&5<=t[r]){var E=t[1],A=c[E];"undefined"!=typeof A&&(A.aa(h(t[3],10),h(t[4],
10),6==t[r]?t[5]:void 0),A.R()||(g[E]=A))}}return g},F=function(a,c){var b=a[m](".");return"string"==typeof c&&0<b[r]&&b[0]!=c?[]:b.slice(1)};var H=function(a,c,b,e,g){this.b=g||H.DEFAULT_ID;this.a=a;this.e=c;this.f=b;this.d=e;this.C=!1};H.experiments_={"Eyv5i1bZTCii9Dx039pVyw":{"api_version":"V1","method":"experiments.get","error":{"code":404,"message":"Experiment not available"}}};H.DEFAULT_ID="Eyv5i1bZTCii9Dx039pVyw";v=H[u];v.l=function(a){if(!this.i()&&!this.w()){var c=new z(f);if(I(c.isEnabled(),"Unable to write cookies")){var b=this.n(a),e=this.u(),g=G(e);g[this.b]=new D(this.b,"0",b);var b=e,k;for(k in g)var p=g[k],b=b.concat(".",p.ba()),e=e.concat(".",p.ca());c.set("__utmx",b,this.d,this.e,this.h());c.set("__utmxx",e,this.d,this.e,this.h());-2!=a[0]&&this.D(a)}}};
v.D=function(a){d.gaData||(d.gaData={});d.gaData.expId=this.b;d.gaData.expVar=this.n(a)};v.h=function(){if("string"==typeof this.a&&""!=this.a&&"none"!=this.a&&"auto"!=this.a)return this.a;if("none"==this.a)return null;var a=""+f.domain;return 0==a.indexOf("www.")?a.substring(4):a};v.u=function(){if(!this.f)return"1";var a=this.h();if(a){var c=1,b=0,e;if(a)for(c=0,e=a[r]-1;0<=e;e--)b=a.charCodeAt(e),c=(c<<6&268435455)+b+(b<<14),b=c&266338304,c=0!=b?c^b>>21:c;a=String(c)}else a="1";return a};
v.n=function(a){for(var c=0;c<a[r];c++)if(-2==a[c])return"";return a.join("-")};v.k=function(a){if(0==a[r])return-2;a=a[m]("-");for(var c=[],b=0;b<a[r];b++)c[b]=h(a[b],10);return c};var I=function(a,c){!a&&c&&console&&console.error&&console.error(c);return a};v=H[u];v.i=function(){var a=d._gaUserPrefs;return a&&a.ioo&&a.ioo()};
v.B=function(){if(!this.C){var a=H.experiments_[this.b];this.C=!0;if(!I("object"==typeof a,"Could not load experiment")||a.error)return!1;this.c=a.data}return I("object"===typeof this.c,"Could not load experiment")};v.t=function(){if(this.i())return-2;var a=this.w();if(a)return a;a=G(this.u())[this.b];if(!a)return-1;a=this.k(a.r);-2!=a&&this.D(a);return a};
v.I=function(){if(this.i()||!this.B())return 0;var a=this.t();if(-2==a||this.Q(a))return 0;if(-1!==a)return a;if(!this.O())return this.l([-2]),0;a=this.U();this.l(a);return a};v.O=function(a){return("number"==typeof a?a:Math.random())<this.c.participation};
v.U=function(a){I("undefined"===typeof _gaq,"Variations should be chosen before hit is sent to GA");a="number"==typeof a?a:Math.random();for(var c=0;c<this.c[l][r];c++){var b=this.c[l][c];if(a<b.weight)return this.k(b.id);a-=b.weight}I(!1,"The combinations weights did not add up to 1");return[0]};v.L=function(a){return this.B()&&I(0<=a&&a<this.c[l][r])?this.c[l][a]:null};
v.w=function(){var a=/#utmxid=[-_a-zA-Z0-9]{22};utmxpreview=(\d{1,2});/.exec(d.location.hash);return a?(a=this.L(h(a[1],10)),this.k(a.id)):null};v.Q=function(a){if("number"===typeof a)return!1;a=this.n(a);for(var c=0;c<this.c[l][r];c++){var b=this.c[l][c];if(b.id==a)return b.disabled}I(!1,"Unable to locate combination with id "+a);return!0};C=C||{};C.H=0;x("cxApi.ORIGINAL_VARIATION",C.H,void 0);C.G=-1;x("cxApi.NO_CHOSEN_VARIATION",C.G,void 0);C.F=-2;x("cxApi.NOT_PARTICIPATING",C.F,void 0);C.p="auto";x("cxApi.DEFAULT_DOMAIN",C.p,void 0);C.q=48211200;x("cxApi.DEFAULT_EXPIRATION_SECONDS",C.q,void 0);C.o="/";x("cxApi.DEFAULT_COOKIE_PATH",C.o,void 0);C.a=C.p;C.e=C.o;C.f=!0;C.d=C.q;C.W=function(a,c){I("string"==typeof c||"undefined"==typeof c,"Invalid experiment id: "+c)&&(new H(C.a,C.e,C.f,C.d,c)).l([a])};
x("cxApi.setChosenVariation",C.W,void 0);C.$=function(a){I("string"==typeof a,"Invalid domain name: "+a)&&(C.a=a)};x("cxApi.setDomainName",C.$,void 0);C.Y=function(a){I("string"==typeof a,"Invalid cookie path: "+a)&&(C.e=a)};x("cxApi.setCookiePath",C.Y,void 0);C.V=function(a){I("boolean"==typeof a,"Invalid value for allowHash: "+typeof a)&&(C.f=a)};x("cxApi.setAllowHash",C.V,void 0);C.X=function(a){I("number"==typeof a,"Invalid cookieExpirationSeconds: "+a)&&(C.d=a)};
x("cxApi.setCookieExpirationSeconds",C.X,void 0);C.J=function(a){I("string"==typeof a||"undefined"==typeof a,"Invalid experiment id: "+a);a=(new H(C.a,C.e,C.f,C.d,a)).I();return"number"===typeof a?a:a[0]};x("cxApi.chooseVariation",C.J,void 0);C.K=function(a){I("string"==typeof a||"undefined"==typeof a,"Invalid experiment id: "+a);a=(new H(C.a,C.e,C.f,C.d,a)).t();return"number"===typeof a?a:a[0]};x("cxApi.getChosenVariation",C.K,void 0);})();
